[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "uav-sim"
version = "0.1.0"
description = "UAV flight, aerodynamic and CFD simulation platform"
requires-python = ">=3.11"

dependencies = [
    "numpy",
    "scipy",
    "matplotlib",
    "pyyaml",
    "pyvista",
    "vtk"
]

[tool.setuptools.packages.find]
where = ["src"]
